import streamlit as st

st.title("How Vexa Works")

st.markdown("""
**Visibility-as-a-Service (VaaS)** is a new model that lets businesses inject their content into the answers generated by AI platforms like GPT.

### ⚙️ How It Works
1. You submit your content via this portal.
2. Vexa processes it using AI embeddings (MiniLM).
3. Your content is stored and matched by context.
4. AI platforms query Vexa to enrich their answers.
5. Your brand shows up *within* relevant responses.

All without ads — just smart visibility.
""")